### ISSUE TITLE
Email and Phone number doesn't show

### ISSUE THREAD

**Issue by navoda123** [bluebits-academy/mern-stack-ecommerce#14]
![Screenshot_1624004473](https://user-images.githubusercontent.com/86100884/122530603-45a52c80-d03c-11eb-8bc7-44562b783046.png)

```
undefined is not an object (evaluating 'order.user._id')
at Screens\User\UserProfile.js:44:31 in axios.get.then$argument_0
at [native code]:null in filter
at Screens\User\UserProfile.js:43:12 in axios.get.then$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue
at [native code]:null in flushedQueue
at [native code]:null in callFunctionReturnFlushedQueue
```

**Comment by navoda123** [comment]
Email and Phone number doesn't show and also the Orders Doesn't show

**Comment by kamrul91111** [comment]
axios.get(`${baseURL}users/${context.stateUser.user.userId}`, modify the get request

**Comment by navoda123** [comment]
@kamrul91111 Thank You So Much It Works!!

**Comment by Ali-Raza-400** [comment]
@kamrul91111 thanks
